version: "3.8"

services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    image: fe-data-formulator
    container_name: fe-data-formulator
    ports:
      - "5070:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dev-net

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    image: be-data-formulator
    container_name: be-data-formulator
    ports:
      - "5071:5000"
    volumes:
      - ./data:/app/data-formulator/data
    environment:
      - LOCAL_DB_DIR=/app/data-formulator/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dev-net

networks:
  dev-net:
    name: dev-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
